name: CI

on:
  push:
    branches:
      - "ci-*"
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        continue-on-error: false

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@b00af27efadbc7b4ca8b82abbd903b17cc874d2a # v1
        continue-on-error: false

      - name: Install forge-std
        run: forge install foundry-rs/forge-std@v1.16.2 --no-git
        continue-on-error: false

      - name: Build contracts
        run: forge build
        continue-on-error: false

      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
        continue-on-error: false

      - name: Install npm dependencies - clean install
        run: npm ci
        continue-on-error: false

      - name: Lint
        run: npm run lint:check
        continue-on-error: false

      - name: Verify on-chain
        run: npm run verify
        continue-on-error: false
